### ISSUE TITLE
Links to GitHub on the About page

### ISSUE THREAD

**Issue by goldbergtatyana** [MusicConnectionMachine/VisualizationG6#100]
Do we need to have links to GitHub for all members of the seminar?

How about asking in the lobby for preferences of the people? Let's give everyone two days to reply, If there will be no reply, let's keep the links to GitHub. Otherwise, links to other pages or no active links at all.

**Comment by kordianbruck** [comment]
We asked already today in the main channel. Will update it on a request basis. I think its important to link back to the profiles as it turns up in google if someone is looking at references for a person.

**Comment by pfent** [comment]
Solved in #96
