### ISSUE TITLE
Plain background

### ISSUE THREAD

**Issue by goldbergtatyana** [MusicConnectionMachine/VisualizationG6#102]
The current wallpaper looks a bit childish with the many symbols. Lets have it just plain white.

**Comment by kordianbruck** [comment]
I actually like it... Plain white will be really boring :cry:

**Comment by goldbergtatyana** [comment]
The matter of taste again it seems :)

Lets have more people give us their opinion then

**Comment by syncall** [comment]
An alternative could also be to elevate some 'main' background in white, such like the following

![grafik](https://cloud.githubusercontent.com/assets/25962345/25315766/f7253bbe-285a-11e7-84a4-f9930b63be4a.png)

**Comment by gyachdav** [comment]
+1

Looks very nice

**Comment by kordianbruck** [comment]
Done for now.
