### ISSUE TITLE
Fix pagination with API

### ISSUE THREAD

**Issue by syncall** [MusicConnectionMachine/VisualizationG6#104]
At the moment pagination isn't really working
Dependent on 

- [x] MusicConnectionMachine/api#126
- [x] MusicConnectionMachine/api#125

**Comment by pfent** [comment]
The two referenced issues are closed now.

**Comment by kordianbruck** [comment]
@Binabiko maybe you can jump in and finish this up please?

**Comment by kordianbruck** [comment]
@syncall thanks!
