### ISSUE TITLE
Sources of icons in the widgets

### ISSUE THREAD

**Issue by chaoran-chen** [MusicConnectionMachine/VisualizationG6#115]
The widgets use several icons from flaticon.org. The sources are documented in https://github.com/MusicConnectionMachine/VisualizationG5/blob/develop/docs/image_sources.md and have to be inserted as described here:
http://support.flaticon.com/hc/en-us/articles/207248209-How-I-must-insert-the-attribution-

**Comment by joern-vh** [comment]
@kordianbruck Should I add six entries to the attribution table? We need to list every icon from different authors.

**Comment by gyachdav** [comment]
Add only one entry named flat icon and in the reference column put the refs to all six icons. In the description column write that these icons were used for the relations widget.

**Comment by chaoran-chen** [comment]
Not only for the relations widget, every widget uses some.

**Comment by joern-vh** [comment]
Closed by #125.

**Comment by kordianbruck** [comment]
@Binabiko please leave the issues open, till the code is merged! Thank you!

**Comment by kordianbruck** [comment]
@Binabiko now its merged. So one can close. :dancer:
