### ISSUE TITLE
Create Search Page

### ISSUE THREAD

**Issue by demirdagemir** [MusicConnectionMachine/VisualizationG6#13]
Create the landing page with search bar

**Comment by syncall** [comment]
When the elastic search server is running, you cann query it like this
https://www.elastic.co/guide/en/elasticsearch/reference/5.2/_the_search_api.html

**Comment by syncall** [comment]
For example with a get request http://localhost:9200/music/_search?q=mozart&from=0&size=10
For the human eye: http://localhost:9200/music/_search?q=mozart&from=0&size=10&pretty 
or a more complex POST request

**Comment by sacdallago** [comment]
@syncall that, given that you are running the elasearch server locally :D Trust me.. not everyone... will get it.
