### ISSUE TITLE
Search for tags

### ISSUE THREAD

**Issue by chaoran-chen** [MusicConnectionMachine/VisualizationG6#131]
I just recognized that the Tags are linked, clicking on `20th-century classical musicians` redirects, for example, to `/search/20th-century%20classical%20musicians` which shows nothing. Either we implement a tag-search or remove the link.

**Comment by kordianbruck** [comment]
naice!

**Comment by kordianbruck** [comment]
Wait, you just removed the click handler - I call hacks!
