### ISSUE TITLE
Get initial routing working

### ISSUE THREAD

**Issue by demirdagemir** [MusicConnectionMachine/VisualizationG6#17]
A simple **react router(v4)** will be integrated.

- When the user types in the search bar, the app will navigate to `/search`, for search results.
- Existing routes can be then be modified if we want to. 
- Additional routes can be easily added to the `App` component, where the React Router will live.

**Comment by pfent** [comment]
Could you please provide a short description with each issue?
E.g. What routes do you want to provide? What tools are you using?

Even a short note, stating you haven't decided on anything, helps you and your coworkers keeping track of decisions

**Comment by kordianbruck** [comment]
@demirdagemir please link the commits by including them in the commit / PR (simply type "#\<issueNumber>")

or add a description when closing the issue what was done
