### ISSUE TITLE
Build component for graph

### ISSUE THREAD

**Issue by syncall** [MusicConnectionMachine/VisualizationG6#22]
Use D3. As input you get an id. With this the Backend can be queried to get additional info. Display connections to other entries in the graph. Nodes should be click able to navigate to the other entries.

**Comment by syncall** [comment]
Maybe background transparent?

**Comment by kordianbruck** [comment]
What kind of graph? You mean the network graph? Are there any mockups? Which ID? 

This issue is way too unspecific

**Comment by syncall** [comment]
Done by team 5
