### ISSUE TITLE
Build component for commenting

### ISSUE THREAD

**Issue by syncall** [MusicConnectionMachine/VisualizationG6#23]
In Elasticsearch, data can easily be added to indices. Make new index and type for comments. Anonymous user has to have the right to insert into this index.
Maybe use some sort of HTML "What you see is what you get editor" (-> Google) for formating the comment.

**Comment by syncall** [comment]
Input is a id (+maybe a type = string) together these are unique. They is references a entry under /music/:type/:id

**Comment by syncall** [comment]
Prevent HTML Injection

**Comment by demirdagemir** [comment]
HTML injection/XSS should we really be concerned about? My guess is 

1-  React takes care of that.
2- It's a backend job to escape strings? 🤔

**Comment by syncall** [comment]
If users can input custom text we have to think about it. At least check if its not possible

**Comment by kordianbruck** [comment]
XSS is generally to be handled by your templating system when outputting / inserting variables into your generated HTML code. With react some cases are considered. This seems to be a good read: https://medium.com/node-security/the-most-common-xss-vulnerability-in-react-js-applications-2bdffbcc1fa0#.jteym9x4e

I'm no friend of saving HTML entities to DB - here is why: https://stackoverflow.com/questions/9299152/do-i-need-to-use-html-entities-when-storing-data-in-the-database

But I'm hijacking this issue - please split this discussion into a new issue.

**Comment by kordianbruck** [comment]
We are dismissing comments for now. 

We are not using elasticsearch for anything except demo purposes.
