### ISSUE TITLE
Build some animations between transitions

### ISSUE THREAD

**Issue by syncall** [MusicConnectionMachine/VisualizationG6#24]
For example Loading icon etc.

**Comment by syncall** [comment]
https://facebook.github.io/react/docs/animation.html

**Comment by kordianbruck** [comment]
@demirdagemir so this has been implemented? In which PR?

**Comment by demirdagemir** [comment]
@kordianbruck No, I closed this as in "will be done in a later date", like in a backlog manner, issues started to get crowded. Wrong approach?

**Comment by kordianbruck** [comment]
Great - leaving a comment lets everyone know about your plans ;)

**Comment by demirdagemir** [comment]
Alright, thanks a lot 👍

**Comment by demirdagemir** [comment]
Reopened since it was postponed before

**Comment by kordianbruck** [comment]
Still: not an important issue. We have to have the main page finished before doing detailed work.
