### ISSUE TITLE
Build Bridge from Elasticsearch to database of team A&B

### ISSUE THREAD

**Issue by syncall** [MusicConnectionMachine/VisualizationG6#27]
Elasticsearch offers two possibilities. Rivers (easy but deprecated) and logstash (extra application)
https://www.elastic.co/guide/en/logstash/current/index.html
Think of proper index and type (all types under same index can be searched the same tame)

**Comment by kordianbruck** [comment]
Teams 1 & 2 will have to provide an REST Api for you guys, not a database.

**Comment by syncall** [comment]
Elasticsearch is just for mock-up. Well only use the api
