### ISSUE TITLE
Write tests for components

### ISSUE THREAD

**Issue by demirdagemir** [MusicConnectionMachine/VisualizationG6#31]
Ideally this could be postponed but we need it for the presentation

**Comment by demirdagemir** [comment]
Check out JEST, Mocha, Chai, Istanbul ( for test coverage )

**Comment by kordianbruck** [comment]
Maybe even https://www.sonarqube.org/ ?

**Comment by demirdagemir** [comment]
Wow, seems really nice @kordianbruck

**Comment by kordianbruck** [comment]
No time for tests at the moment. Will revisit testing UI when we got time.
