### ISSUE TITLE
Set up docker cloud and send reports 

### ISSUE THREAD

**Issue by demirdagemir** [MusicConnectionMachine/VisualizationG6#33]
> show us screenshots and mockups. Make your code run on Heroku or similar hosting services. Set up continuous deployment if you feel up for that challenge.

**Comment by sacdallago** [comment]
Edit: Set up docker cloud as in https://github.com/MusicConnectionMachine/MusicConnectionMachine.github.io/issues/6

**Comment by demirdagemir** [comment]
Elasticsearch API & Data : http://elasticsearch-a2e1f328-1.352d537d.cont.dockerapp.io:9200/
UI : http://visualization-g6.surge.sh/

**Comment by kordianbruck** [comment]
@demirdagemir are you guys still planing to use Azure?

**Comment by demirdagemir** [comment]
@kordianbruck I think we are. The elastic search image in the docker cloud that Christian has set up, is connected to Azure, I believe. 🤔

**Comment by kordianbruck** [comment]
Ah great - looks greaaaaat! Keep it up!

**Comment by demirdagemir** [comment]
@kordianbruck just one question, do we have to send additional reports, or updating the readme just did it?

**Comment by kordianbruck** [comment]
What do you mean by reports? You mean like on friday? No, we will see your progress in your presentation next week - no need for more reports. Keeping the README up to date is also great ;)

**Comment by demirdagemir** [comment]
Yes, I mean like you said on Gitter, that show us screenshots, mockups, deploy the app. Alright then, thanks a bunch :)

**Comment by kordianbruck** [comment]
No thats fine, if you handed them in on friday.

**Comment by demirdagemir** [comment]
Oh, that's what I meant. We haven't handed anything in because of these deploying problems. The app didn't work because we couldn't deploy the backend. (It took waaaaaaay longer than we expected) So should I send an e-mail to jstech address?

**Comment by kordianbruck** [comment]
Yes, please do!

**Comment by demirdagemir** [comment]
Alright, sorry for the inconvenience
