### ISSUE TITLE
Can't deploy docker

### ISSUE THREAD

**Issue by demirdagemir** [MusicConnectionMachine/VisualizationG6#34]
We are yet to send the report because we can't deploy our docker image to the docker cloud. Could one of tutors help us? We tried bunch of things for 2 days but we simply can't find a solution.

We kind of lack experience in this and we need some guidance. 

The problem is, when we add a service to the docker cloud, it terminates itself, throwing bunch of memory errors. (map count not enough, bootstrapping failed, etc.)

**Comment by demirdagemir** [comment]
Solved

**Comment by kordianbruck** [comment]
Please next time mention one of us or post it in chat to get priority support on this ;)

**Comment by sacdallago** [comment]
@kordianbruck in @demirdagemir 's defence: He did :) But I was a 🐒
