### ISSUE TITLE
Get Elasticsearch to run on Azure

### ISSUE THREAD

**Issue by syncall** [MusicConnectionMachine/VisualizationG6#36]
For demonstration purpose (and maybe later finally) we have to get Elasticsearch to run on the azure cloud.

**Comment by syncall** [comment]
Whenever I start Elasticsearch, an error comes up stating, that vm.max_map_count is too low
This is actually a kernel setting. 
@ysdevys @sacdallago Do you have any idea how to fix that? 
`sysctl -w vm.max_map_count=262144` would fix the problem, but I can't run that command in a container. Docker containers share the kernel with the host, so is this a host setting?

**Comment by demirdagemir** [comment]
This problem is solved, I finally made it work yesterday.  Sorry I didn't let you know, I thought you saw the last commit #35,   and checked out the issues: #33 #34

**Comment by sacdallago** [comment]
Docker cloud was also behaving strangely over the weekend, might have been that. In two days I'll give you better access to the resources, am talking to the MS guys how to set this up best ;)
