### ISSUE TITLE
Create Map Component

### ISSUE THREAD

**Issue by joern-vh** [MusicConnectionMachine/VisualizationG6#42]
Creating a Map with an Overview on where Events happened.

**Composers/Musicians:**
- Where did they born?
- Where did they composed?
- Where did they performed?

**Music Pieces**
- Where have they been composed?
- Where have they been performed?

We need to have a look what kind of Data we can get.

Think this is assigned to @ysdevys right?

**Comment by joern-vh** [comment]
Unfortunately I cannot assign anyone to this Issue - Problem because it's Group 6?

**Comment by ysdevys** [comment]
Yes, its mine

**Comment by ysdevys** [comment]
URL to the issue of G5 where all the relevant comments are:
https://github.com/MusicConnectionMachine/VisualizationG5/issues/26

**Comment by ysdevys** [comment]
Feature/map-widget deafult committed:
https://github.com/MusicConnectionMachine/VisualizationG6/tree/feature/map-widget

I will continue working on the functionallity of the map.

**Comment by ysdevys** [comment]
Travis build passed for the feature and for the pull request.
https://travis-ci.org/MusicConnectionMachine/VisualizationG6

**Comment by ysdevys** [comment]
done 
PR:
https://github.com/MusicConnectionMachine/VisualizationG6/pull/66
