### ISSUE TITLE
Integrate Relations in Search Results

### ISSUE THREAD

**Issue by syncall** [MusicConnectionMachine/VisualizationG6#51]
When searching for something we display some interesting relations regarding the search words.
For this we load the sample data from MusicConnectionMachine/RelationshipsG4#49 into elasticsearch

**Comment by kordianbruck** [comment]
- I don't understand this? 
- You are still using elasticsearch? 
- "Wan't" 
- Whaaaaat?

**Comment by demirdagemir** [comment]
I'm guessing what @syncall mean is after submitting a search term, say, Mozart; we want to display some relations like "born in", "similar composers" afterwards. (Spotify-like interface, as we discussed during the presentation week.)

And we are still using elasticsearch for the API. Did we miss it or is the API ready? @kordianbruck

**Comment by kordianbruck** [comment]
No, no elasticsearch anywhere in the stack. We said instead revert to SQL Fulltext so that we reduce complexity and improve maintainability

**Comment by kordianbruck** [comment]
Also, how does this relate to https://github.com/MusicConnectionMachine/VisualizationG5/pull/50 ?

Aren't you basically talking about the same thing?

**Comment by lustoykov** [comment]
Yep, I think so.

**Comment by syncall** [comment]
This one is for general search results. The app from the other team is similar but only for one entity.
@kordianbruck so you actually suggest I should set up a complete new mock-up back end, that works with postgres? Even when the API call would be the same anyway?

**Comment by kordianbruck** [comment]
@syncall No: for the mockup you can work with elastic. For the end product we don't want it in there. Sorry for the confusion.

**Comment by syncall** [comment]
Yes that's what I thought. Maybe I shouldn't have written it in the issue description, because it's only temporary.
