### ISSUE TITLE
Integrate Widgets

### ISSUE THREAD

**Issue by syncall** [MusicConnectionMachine/VisualizationG6#55]
Refering to MusicConnectionMachine/VisualizationG5#42
Probably through iframe. They have some other closed issue regarding this topic

**Comment by chaoran-chen** [comment]
If you want, our groups can work on this issue together. Just write us if you need something! :)

**Comment by demirdagemir** [comment]
Will do definitely, thanks a lot 😄

**Comment by demirdagemir** [comment]
@chaoran-chen I saw you guys are working on new ideas, mockups; should we wait a little bit more for this?

**Comment by chaoran-chen** [comment]
I think that you can already start to integrate the Timeline-Component, it is for the most part finished and only needs to be connected to the API. The relationship-exploration widget is still early in the development phase but I guess that later, it can be integrated in the same way like the Timeline-Component.

**Comment by kordianbruck** [comment]
- [ ] On each of the search results pages we want to display events, a map and the relationship widget anchored around the current entity.

**Comment by pfent** [comment]
Follow up from https://github.com/MusicConnectionMachine/VisualizationG5/issues/65:

Documentation about integration of Widgets is [here](http://54.68.164.199:8083/)

**Comment by goldbergtatyana** [comment]
Once a search item is enetered, will the user be immediately forwarded to the result page with events, map and relationship widgets? If so, will then the table that is currently shown go away?
