### ISSUE TITLE
Implement Autocomplete

### ISSUE THREAD

**Issue by syncall** [MusicConnectionMachine/VisualizationG6#57]
Group 5 already has one -> Copy?

Maybe: https://www.npmjs.com/browse/keyword/typeahead

**Comment by demirdagemir** [comment]
Why? We don't need autocomplete. We have redux? (Not to say autocomplete is bad, but already we have an alternative)

**Comment by syncall** [comment]
It's still something different. Autocomplete is there to suggest you new stuff you haven't typed yet. But true. It's just nice to have with redux I think. Maybe we can get it to work until feature freeze
