### ISSUE TITLE
Create the First Draft of Design

### ISSUE THREAD

**Issue by demirdagemir** [MusicConnectionMachine/VisualizationG6#6]
First draft of Design of the opening page

**Comment by yetolas** [comment]
I will create the wiki page with comments on tools and design files.

**Comment by yetolas** [comment]
I found this tool online called Axure for creating mockups and was pretty straight forward: https://www.axure.com

So here is what I created, comment first on the functionalities and what I miss and then on how do we want to look like: http://6ua191.axshare.com/#g=1&p=home

Send me all feedback possible so I can add/ correct it.

**Comment by ysdevys** [comment]
I like it

**Comment by syncall** [comment]
Nice. Should we split the search page and the page with the details? So we have a general search page like this:
<---Search Bar--->

-- Result 1
-- Result 2
etc

And if you click on one entry you get the page @yetolas made? Different pages for Musicians and Compositions?

And single react components for the graph and the details. So they could be include elsewhere. You just have to know the Composition/Musician name

For the Graph. Make big knots for people and small for compositions? Make Node clickable to move to another cpmosition.
