### ISSUE TITLE
Header Bar & Footer

### ISSUE THREAD

**Issue by kordianbruck** [MusicConnectionMachine/VisualizationG6#67]
Use bootstrap components for this.

The header bar should contain:
- TUM Logo
- MCM Logo (Provided @vviro - put a placeholder there for now)
- Navigation bar

Footer - three columns with the following
* The MusicConnectionMachine
** About ( Static Page )
** Legal ( Static Page )
** Github ( https://github.com/MusicConnectionMachine )
* Partners
** Rostlab ( https://www.rostlab.org )
** Peachnote ( http://www.peachnote.com )
** IMSLP ( http://imslp.org/ )
* Social (Placeholders for now)
** Facebook
** Twitter
** G+

**Comment by sacdallago** [comment]
Uhm @kordianbruck @gyachdav @goldbergtatyana you know the story of the TUM logo and design of the page, right? Do we want to go there? I vote for a sound **NO**

**Comment by syncall** [comment]
@kordianbruck you said you want a navigation in the Header. Where should it navigate to? 
The only thing I can think of is maybe the About Page from the Footer, or the Widget Explanation of Team 5?

**Comment by gyachdav** [comment]
We will have Home, search and about. 
Search is the page where we will be able to search the entities list. The rest is self explanatory.

**Comment by gyachdav** [comment]
@sacdallago TUM logo is fine as long as we follow the same format we had in got.show. Let's just copy the header and footer from there.

**Comment by gyachdav** [comment]
navigation bar continued at #77

**Comment by syncall** [comment]
This should be done unless someone wants some more changes
