### ISSUE TITLE
Add version & copyright 

### ISSUE THREAD

**Issue by kordianbruck** [MusicConnectionMachine/VisualizationG6#68]
On the left we should show the version hash of git ( Use something like https://www.npmjs.com/package/git-rev-sync )

On the Right we want to have a copyright notice with the current year and CC4.0 attribution (Link to https://creativecommons.org/licenses/by/4.0/)

**Comment by syncall** [comment]
Just one line at the bottom of the page like this?
`v1.0.0` (left side) `© 2017 MusicConnectionMaschine` (right side)
