### ISSUE TITLE
Static pages

### ISSUE THREAD

**Issue by kordianbruck** [MusicConnectionMachine/VisualizationG6#69]
Set up static pages for:

* [x] legal
* [x] imprint
* [x] attributions

You can copy some content from https://got.show

**Comment by yetolas** [comment]
I will add the pages to another branch so you can check it out.

**Comment by kordianbruck** [comment]
Thanks @yetolas

**Comment by yetolas** [comment]
Commited them, hope everything works fine!

**Comment by kordianbruck** [comment]
great work @yetolas - thanks a lot.

This can be closed.
