### ISSUE TITLE
Refactor start page

### ISSUE THREAD

**Issue by kordianbruck** [MusicConnectionMachine/VisualizationG6#70]
On the start page we want to have all widgets shown with a preselected set of entities that really show off nicely how we have processed the data (Switch through with tabs or something)

Each time the page is loaded we can randomize the order of the entities.

**Comment by kordianbruck** [comment]
![img_20170423_172157](https://cloud.githubusercontent.com/assets/298860/25314816/1ff3fa72-284b-11e7-9002-6f76376f66fb.jpg)

**Comment by kordianbruck** [comment]
With each of the widgets we will display a screenshot of the widget. Once a user clicks on it we redirect to the entity page and actually show the widget interactively.

**Comment by demirdagemir** [comment]
I'm working on this.. What's the text above the Footer?

**Comment by goldbergtatyana** [comment]
We will post a link to the text for the website in a few moments here

**Comment by kordianbruck** [comment]
@demirdagemir Its 'Czech out our Stats'

**Comment by goldbergtatyana** [comment]
The text for the About page and the Landing page can be found at https://docs.google.com/document/d/1np2dw3D_B7Gt1bYzsqOOf2_7zK9CIiP_eqY3FyJ-VPQ/edit

**Comment by kordianbruck** [comment]
Done for now.
