### ISSUE TITLE
About Page

### ISSUE THREAD

**Issue by kordianbruck** [MusicConnectionMachine/VisualizationG6#73]
- Will contain a text that describes the project ( TODO by @vviro @gyachdav )
- Our group picture that @sacdallago will post
- name of all students that participated

**Comment by sacdallago** [comment]
![js2017](https://cloud.githubusercontent.com/assets/6240943/25118576/2be4b28c-2417-11e7-86de-ab8faed1ebe7.jpg)

**Comment by pfent** [comment]
A link to the development documentation about embedding our widgets should also be on the about page

**Comment by kordianbruck** [comment]
Merged.
