### ISSUE TITLE
Social Channels

### ISSUE THREAD

**Issue by syncall** [MusicConnectionMachine/VisualizationG6#75]
To which Social Channels should the Page be linked?

**Comment by goldbergtatyana** [comment]
keep them as place holders for now pls. we'll take care of social channels at the very end. thanks :)

**Comment by syncall** [comment]
ok, thanks

**Comment by sacdallago** [comment]
Well, but I'd still keep the issue open, low prio, reminds us to take care of this :)

**Comment by syncall** [comment]
Should there be also buttons for the TUM Facebook page?
In the CD it says the following: 

![grafik](https://cloud.githubusercontent.com/assets/25962345/25227878/7fb0e0b6-25ca-11e7-8113-faa7f1c6e965.png)

**Comment by kordianbruck** [comment]
Yes, why not - lets add both in that fashion.

**Comment by kordianbruck** [comment]
Disregard my previous comment. The way it looks now is very nice!
