### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by syncall** [MusicConnectionMachine/VisualizationG6#76]
Hi, is there any Logo we should use for the MusicConnectionMachine? Big one and Small one? Or should we keep our own?

**Comment by sacdallago** [comment]
Pinging @vviro for this. Or any artist in the group @MusicConnectionMachine/group-1 @MusicConnectionMachine/group-2 @MusicConnectionMachine/group-3 @MusicConnectionMachine/group-4 @MusicConnectionMachine/group-5 ? :)

**Comment by gyachdav** [comment]
Worse case scenario just have the name MusicConnectionMachine appear at the header.

**Comment by sacdallago** [comment]
**MCM** anyone 😆 ? 
![](https://upload.wikimedia.org/wikipedia/en/1/1d/MCM-logo.png) ![](https://upload.wikimedia.org/wikipedia/commons/8/86/MCM_logo.png)

**Comment by goldbergtatyana** [comment]
let' ask in the gitter lobby if there are create minds in the group who could come up with a better logo than @sacdallago 😆

**Comment by ManekenT** [comment]
Hi, @chaoran-chen told me about this project and your search for a logo. Some quick ideas:  

<img src="https://cloud.githubusercontent.com/assets/5783049/25284477/5ea5c07e-26b7-11e7-813b-b6eff87c5076.png" width="250">
<img src="https://cloud.githubusercontent.com/assets/5783049/25284587/bdebc24a-26b7-11e7-98bf-425cdbb546f0.png" width="250">
<img src="https://cloud.githubusercontent.com/assets/5783049/25284598/c9e51060-26b7-11e7-88af-a30cc887c92a.png" width="250">

**Comment by syncall** [comment]
@ManekenT Cool I like this minimalistic style! The first or second would fit nicely in the Header (instead of MusicConnectionMachine). 
Have you seen the [Demo](http://webpageg6.8ed630ce.svc.dockerapp.io/)? We'll probably change the overall styling (colors..) of the site, so don't take that as a reference, but do you think you can adapt the third logo to something with a bit more width so it can span the whole page?

And do you think you can make a tiny version ([Favicon](https://de.wikipedia.org/wiki/Favicon)) as well? One that can be placed inside the adressbar.

**Comment by ManekenT** [comment]
@syncall I would advise against using two different designs at once (maybe I misunderstood you?). Also the first idea works well (imo) with the text written out, the abbreviation, and as a favicon:

![mcm_long](https://cloud.githubusercontent.com/assets/5783049/25304973/ce267a86-2772-11e7-8c2b-ad3c0490462e.png)
![favicon](https://cloud.githubusercontent.com/assets/5783049/25304974/cf26b446-2772-11e7-9689-c07f18cd4c76.png)
(you can use https://realfavicongenerator.net/ to generate all needed favicon sizes)

**Comment by sacdallago** [comment]
This looks cool @ManekenT :) Thanks!

**Comment by ManekenT** [comment]
Here are the source files, both as Illustrator files and .svg's:
[mcm.zip](https://github.com/MusicConnectionMachine/VisualizationG6/files/949057/mcm.zip)

**Comment by syncall** [comment]
@ManekenT Thanks. Nice! But can you reduce the width and height of the logos to the absolute minimum? With no space between the Word and the border? And the background to transparent?

**Comment by syncall** [comment]
its just hard to fit it like this
![grafik](https://cloud.githubusercontent.com/assets/25962345/25305839/022542da-2783-11e7-9149-568ea180251f.png)

**Comment by ManekenT** [comment]
yeah of course. should I change the color of the of the logo as well? maybe black or blue?

**Comment by kordianbruck** [comment]
So we have two options for the menu bar:
1. Make the menu bar black/greyish
2. Make the logo transparent with a greyish font color

For the big one: 
I think it can be greyish there, but we want to have less space on the top/bottom

**Comment by goldbergtatyana** [comment]
Thanks @ManekenT for the beautifule logo! Yeah, it would be awesome if you could provide also some alternative colors (black, TUM-blue), maybe grey. 

@kordianbruck best would be to have screenshots with a couple of options and then decide

**Comment by gyachdav** [comment]
I actually prefer the black over white (third option in @MenekenT post) with the name written in a tree line layout.  

@ManekenT thanks a lot for your contribution!!

**Comment by ManekenT** [comment]
Ok, some different options for you to try out. All three versions, each one in white, black, blue and grey.
[mcm.zip](https://github.com/MusicConnectionMachine/VisualizationG6/files/949130/mcm.zip)

**Comment by kordianbruck** [comment]
fixed in #90. Thanks @ManekenT
