### ISSUE TITLE
Navigation bar

### ISSUE THREAD

**Issue by gyachdav** [MusicConnectionMachine/VisualizationG6#77]
Navigation bar should include the following items

- Search - search page 

- Plug ins - link to widget's documentation 

- API  - link to API documentation site

- About

**Comment by syncall** [comment]
At the moment we have the search bar inside the header(navigation) should
we keep it like this and not have an extra link to the search page?

Guy <notifications@github.com> schrieb am Mi., 19. Apr. 2017, 14:32:

**Comment by gyachdav** [comment]
Yup keep it on the right side for now.

**Comment by goldbergtatyana** [comment]
What do you think of having another separate page dedicated to the statistics of the project?

**Comment by gyachdav** [comment]
Order of Nav bar should be (from left to right)

- Home
- Search
- Embed
- Statistics
- About
