### ISSUE TITLE
Corporate Design guidlines

### ISSUE THREAD

**Issue by sacdallago** [MusicConnectionMachine/VisualizationG6#78]
Hi, I will dump all CD related stuff in this issue.

There are guidlines for general how-to build the web site, colour scheme, header & footer and there are two .zip files with the logo in white or blue, which in turn require you to use a specific background and colour scheme :)

[Manual_CD_2016_v1.pdf](https://github.com/MusicConnectionMachine/VisualizationG6/files/941804/Manual_CD_2016_v1.pdf)
![screen shot 2017-04-20 at 10 08 28](https://cloud.githubusercontent.com/assets/6240943/25222648/5277df70-25b9-11e7-96bc-e5ff8041757c.png)
[TUM - Styleguide Web – Responsive Design.pdf](https://github.com/MusicConnectionMachine/VisualizationG6/files/941805/TUM.-.Styleguide.Web.Responsive.Design.pdf)
[TUM - Barrierefreiheit.pdf](https://github.com/MusicConnectionMachine/VisualizationG6/files/941802/TUM.-.Barrierefreiheit.pdf)
[TUM - Icons, Favicon, Touch Icons.pdf](https://github.com/MusicConnectionMachine/VisualizationG6/files/941803/TUM.-.Icons.Favicon.Touch.Icons.pdf)
[TUM - Footer.pdf](https://github.com/MusicConnectionMachine/VisualizationG6/files/941801/TUM.-.Footer.pdf)
[TUM - Rechte Randspalte.pdf](https://github.com/MusicConnectionMachine/VisualizationG6/files/941807/TUM.-.Rechte.Randspalte.pdf)
[TUM - Inhaltsbereich.pdf](https://github.com/MusicConnectionMachine/VisualizationG6/files/941806/TUM.-.Inhaltsbereich.pdf)
[TUM - Seitenaufbau.pdf](https://github.com/MusicConnectionMachine/VisualizationG6/files/941809/TUM.-.Seitenaufbau.pdf)
[TUM - Header.pdf](https://github.com/MusicConnectionMachine/VisualizationG6/files/941808/TUM.-.Header.pdf)
[TUM - Navigation.pdf](https://github.com/MusicConnectionMachine/VisualizationG6/files/941810/TUM.-.Navigation.pdf)
[TUM_Web_Logo_neg.zip](https://github.com/MusicConnectionMachine/VisualizationG6/files/941811/TUM_Web_Logo_neg.zip)

**Comment by syncall** [comment]
so we have to do all this stuff? ... Thats quite some work.
even https://got.show/ isn't conform with all the guidlines.. (few thing I have read: Social Button for TUM is missing. Space around Tum Logo is not enough etc.)

**Comment by sacdallago** [comment]
well, as you have guessed from got.show :D You should try to stick to most of this stuff, but slight deviations are acceptable. This, after all, is not a TUM page. We just want to show the logo on top (for that, there is a quite strict rule though, with spaces, proportions and all). And in general: the colour scheme is useful if you haven't decided on a scheme yet :)

But yeah, I just put _everything_, you take what is needed and what makes sense!

**Comment by kordianbruck** [comment]
Looks good for now.
