### ISSUE TITLE
Contact and gather information about the data structure from Group A/B

### ISSUE THREAD

**Issue by demirdagemir** [MusicConnectionMachine/VisualizationG6#8]

**Comment by syncall** [comment]
Team 05 has already defined some sample data
https://github.com/MusicConnectionMachine/VisualizationG5/tree/develop/mock_data

**Comment by syncall** [comment]
Sample data https://v-private.s3.amazonaws.com/JST2017/composition-metadata.tsv.gz

**Comment by syncall** [comment]
UML datagram from team A http://imgur.com/a/2gRzu

**Comment by sacdallago** [comment]
I can't read anything from the screenshot 🤔

**Comment by kordianbruck** [comment]
@syncall Github also accepts pictures in the issues - just FYI

**Comment by kordianbruck** [comment]
Data was communicated in several other issues in the other repositories. If you are looking for them please check there.
