### ISSUE TITLE
Complete the about page

### ISSUE THREAD

**Issue by kordianbruck** [MusicConnectionMachine/VisualizationG6#88]
current status: http://webpageg6.8ed630ce.svc.dockerapp.io/about

Todo:
- [x] add all the names of all students and link their website / github page. Please ask them over gitter what they prefer.
- [x] add a refernce to attributions on the very bottom like on https://got.show/about
- [x] Implement the text from https://docs.google.com/document/d/1np2dw3D_B7Gt1bYzsqOOf2_7zK9CIiP_eqY3FyJ-VPQ/edit
- [x] Improve the text from above. Do some spellchecking.
- [x] Move the about text to above the picture

**Comment by joern-vh** [comment]
Waiting for final Version of the description text.

**Comment by kordianbruck** [comment]
@Binabiko text is done: https://docs.google.com/document/d/1np2dw3D_B7Gt1bYzsqOOf2_7zK9CIiP_eqY3FyJ-VPQ/edit

**Comment by kordianbruck** [comment]
Quoting from #101:
> Let's move the text of "About the Project" to be above the picture of people from our class. So, that a user reads what the project is about when he gets to the page instead of making scroll down our pic first.

**Comment by gyachdav** [comment]
Remove the header line:

About the Project

**Comment by joern-vh** [comment]
So no "About the Project" at all?

**Comment by gyachdav** [comment]
Nope. This line is redundant.

**Comment by joern-vh** [comment]
Closed by #120.
