### ISSUE TITLE
Gather information about  "Continuous Integration and Testing with JavaScript"

### ISSUE THREAD

**Issue by ysdevys** [MusicConnectionMachine/VisualizationG6#9]
Description: This topic is all about the software development cycle with JavaScript. Starting with behaviour driven development and unit testing (e.g. with Mocha), we then take a look at larger-scale integration testing and especially continuous integration strategies (e.g. with Travis). To finish the testing cycle, we take a look at system and deployment testing (e.g. with Docker).

**Comment by syncall** [comment]
Browsers cache a lot of data <-> .js Files might not be up to date, which makes Continuous Integration difficult?

**Comment by demirdagemir** [comment]
To consider: Do we really need Docker with Webpack?

**Comment by sacdallago** [comment]
@demirdagemir very good point. Rule of thumb:

IF: it runs a server
---> You need docker
ELSE:
---> You don't need docker.


IF: you have written modular javascript/typescript (answer: yes)
---> You need webpack to bundle the src into a bundle
ELSE:
---> You execute the javascript directly from the SRC

Very simple example of this: https://github.com/tpca/mecu-line

Main code is in lib/index.js --> if `npm install` is called, you get a `webpack` boundled version of that code (as browsers cannot interpret instructions such as `module.exports`).

**Comment by yetolas** [comment]
I will update this thread soon with all files and info.

**Comment by yetolas** [comment]
Some tools:
Jenkins
https://www.eriwen.com/tools/continuous-integration-for-javascript/
http://shashikantjagtap.net/javascript-continuous-integration-jenkins-qunit-grunt/
https://codeforgeek.com/2016/04/continuous-integration-deployment-jenkins-node-js/

Jasmine
https://semaphoreci.com/blog/2013/05/28/jasmine-javascript-tests-for-continuous-integration.html
https://code.tutsplus.com/tutorials/testing-your-javascript-with-jasmine--net-21229

Cypress
https://www.cypress.io/

Karma
https://karma-runner.github.io/1.0/index.html

Bamboo
http://blogs.atlassian.com/2010/01/continuous_integration_javascript_jquery_qunit/
https://www.atlassian.com/software/bamboo?_ga=1.204528080.1119597268.1489662587

Team City
https://www.jetbrains.com/teamcity/specials/teamcity/teamcity.html?&gclid=CPfelsrx2tICFYwQ0wodr5IGUw&gclsrc=aw.ds.ds&dclid=COnJicvx2tICFTgC0wodDjkKow

**Comment by kordianbruck** [comment]
It would be great if you can move presentation / workshop related things to a different repository, so we don't get notified about those things! Thanks!

**Comment by ysdevys** [comment]
i sent you all an email with the gathered information and links to some articles and tutorials, that are good
